Feedback360_Frontend/Controllers/UserQueryController.cs
using Feedback360.Infrastructure.EncryptDecrypt;
using Feedback360_Frontend.Models;
using Feedback360_Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Feedback360_Frontend.Controllers
{
    public class UserQueryController : Controller
    {
        public IConfiguration configuration;
        private readonly ILogger<BannerController> _logger;
        Uri baseAddress;
        HttpClient client;
        public UserQueryController(IConfiguration configuration,ILogger<BannerController> logger)
        {
            baseAddress = new Uri(configuration.GetValue<string>("V1BaseUrl"));
            client = new HttpClient();
            client.BaseAddress = baseAddress;
            _logger = logger;
        }

        /// <summary>
        /// - Sprint 3 - by Pooja Patil
        /// UserQueies is a function which returns all available queries for particular user
        /// </summary>
        /// <returns>queries details</returns>
        [HttpGet]
        public ActionResult UserQueries()
        {

            var dashboardSession = SessionHelper.GetObject<AuthResponseDto>(HttpContext.Session, "User");
            if (dashboardSession != null)
            {
                int UserId = dashboardSession.UserID;
                HttpResponseMessage response = client.GetAsync(client.BaseAddress + $"/UserQuery/GetQueriesByUserId?UserId={UserId}").Result;
                string data = response.Content.ReadAsStringAsync().Result;
                dynamic getAllQueries = JsonConvert.DeserializeObject(data);
                ViewBag.allQueries = getAllQueries.data;
                return View("GetUserQueries");
            }
            else
            {
                return RedirectToAction("UserLogin", "User");
            }
        }

        [HttpGet]
        public ActionResult LoadUserQueries()
        {

            var dashboardSession = SessionHelper.GetObject<AuthResponseDto>(HttpContext.Session, "User");
            int UserId = dashboardSession.UserID;
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + $"/UserQuery/GetQueriesByUserId?UserId={UserId}").Result;
            string data = response.Content.ReadAsStringAsync().Result;
            dynamic getAllQueries = JsonConvert.DeserializeObject(data);
            ViewBag.allQueries = getAllQueries.data;
            return PartialView("LoadUserQueries");
        }

    


    /// <summary>
    /// - Sprint 3 - by Pooja Patil
    /// form to create new user query
    /// </summary>
    /// <returns>return to userqueries page after submitting form</returns>
    [HttpGet]
    public ActionResult UserQueryForm()
    {
        var model = new UserQueryVm();
        var dashboardSession = SessionHelper.GetObject<AuthResponseDto>(HttpContext.Session, "User");
        model.UserId = dashboardSession.UserID;
        return PartialView("_UserQueryForm", model);
    }

    /// <summary>
    /// - Sprint 3 - by Pooja Patil
    /// post request form to create new query
    /// </summary>
    /// <param name="userQueryVm">query data to post</param>
    /// <returns>return to userqueries page after submitting form</returns>
    [HttpPost]
    public ActionResult UserQueryForm(UserQueryVm userQueryVm)
    {
        string data = JsonConvert.SerializeObject(userQueryVm);
        StringContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
        HttpResponseMessage response = client.PostAsync(client.BaseAddress + "/UserQuery/AddUserQuery", content).Result;
        return Json(new { Success = response.IsSuccessStatusCode, Message = "User Query Added Successfully!" });
        }

        /// <summary>
        /// - Sprint 3 - by Pooja Patil
        /// shows all related data to single query
        /// </summary>
        /// <param name="id">query id</param>
        /// <returns>returns new view page with all details of single query
        /// and comment box to send comment</returns>
        [HttpGet]
    public ActionResult ViewQueryDetails(string id)
    {
        var dashboardSession = SessionHelper.GetObject<AuthResponseDto>(HttpContext.Session, "User");
        if (dashboardSession != null)
        {
            //int queryid = Int32.Parse(EncryptionDecryption.DecryptString(id));
            var base64Bytes = System.Convert.FromBase64String(id);
            int queryid = int.Parse(System.Text.Encoding.UTF8.GetString(base64Bytes)) / (-99);
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + $"/UserQuery/GetQuery?queryId={queryid}").Result;
            string data = response.Content.ReadAsStringAsync().Result;
            dynamic getQuery = JsonConvert.DeserializeObject(data);
            ViewBag.QueryData = getQuery.data;
            HttpResponseMessage response1 = client.GetAsync(client.BaseAddress + $"/UserQuery/GetCommentsByQueryId?queryId={queryid}").Result;
            string data1 = response1.Content.ReadAsStringAsync().Result;
            List<CommentVm> allComments = JsonConvert.DeserializeObject<List<CommentVm>>(data1);
            if (allComments.Count() == 0)
            {
                TempData["ViewQueryDetails"] = "No Comments Found !";
            }

            return View(allComments);
        }
        else
        {
            return RedirectToAction("UserLogin", "User");
        }
    }

    /// <summary>
    /// - Sprint 3 - by Pooja Patil
    /// post request form to send a comment
    /// </summary>
    /// <param name="commentText">text for enter comment</param>
    /// <param name="queryId">query id to post comment for particular query</param>
    /// <returns></returns>
    [HttpPost]
    public ActionResult SendUserComment(string commentText, int queryId)
    {
        var dashboardSession = SessionHelper.GetObject<AuthResponseDto>(HttpContext.Session, "User");
        string RoleName = dashboardSession.RoleName;
        CreateComment createComment = new CreateComment();
        createComment.CommentText = commentText;
        createComment.QueryId = queryId;
        createComment.RoleName = RoleName;
        string data = JsonConvert.SerializeObject(createComment);
        StringContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
        HttpResponseMessage response = client.PostAsync(client.BaseAddress + "/UserQuery/AddUserComment", content).Result;
        if (response.IsSuccessStatusCode)
        {
            TempData["commentAdded"] = "new comment added successfully";
        }
        return RedirectToAction("UserQueries");
    }
    public JsonResult DeleteUserQuery(int queryId)
    {
        HttpResponseMessage response = client.DeleteAsync(client.BaseAddress + $"/UserQuery/DeleteUserQuery?queryId={queryId}").Result;
        string data = response.Content.ReadAsStringAsync().Result;
        bool IsQueryDeleted = JsonConvert.DeserializeObject<bool>(data);
        if (IsQueryDeleted)
        {
            return Json(true);
        }
        return Json(false);
    }
}
}

Feedback360_Frontend/Views/UserQuery/GetUserQueries.cshtml
@using Feedback360.Infrastructure.EncryptDecrypt
@using Microsoft.AspNetCore.DataProtection
@model IEnumerable<Feedback360_Frontend.Models.CommentVm>
@{
    ViewData["Title"] = "GetUserQueries";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link rel="stylesheet" href="~/css/UserQueries.css" />
<link rel="stylesheet" href="~/css/TableDesign.css" asp-append-version="true" />

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Queries List</h4>
        <p class="card-description">
            <a class="btn btn-info add-new" onclick="loadUserQueryForm(this)" style="color:white;"><i class="fa fa-plus"></i>&nbsp;&nbsp;Add Query</a>
        </p>
         <div id="getAllUserQueries"></div>
            </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/Query/UserQuery.js"></script>
    <script src="~/js/site.js"></script>
}

Feedback360_Frontend/Views/UserQuery/LoadUserQueries.cshtml
@using Feedback360.Infrastructure.EncryptDecrypt
@using Microsoft.AspNetCore.DataProtection
@model IEnumerable<Feedback360_Frontend.Models.CommentVm>

<link rel="stylesheet" href="~/css/UserQueries.css" />
<link rel="stylesheet" href="~/css/TableDesign.css" asp-append-version="true" />

<div class="table-responsive">
            <table class="table" id="QueriesTable">
                <thead>
                    <tr>
                        <th>Query Title</th>
                        <th>Description</th>
                        <th>Query Status</th>
                        <th>View</th>
                        <th>remove</th>

                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in ViewBag.allQueries)
                    {
                        <tr>
                            <td>@item.queryTitle</td>
                            <td>@item.description</td>

                            @if (@item.queryStatus == true)
                            {
                                <td><span id="resolvedQueryStatusBtn">Resolved</span></td>
                            }
                            else
                            {
                                <td><span id="openQueryStatusBtn">Open</span></td>
                            }
                            <td>
                                @{
                                    
                                    var textBytes = System.Text.Encoding.UTF8.GetBytes(((item.queryId)*(-99)).ToString());
                                    string queryIdEnc =  System.Convert.ToBase64String(textBytes);
                                    //string queryIdEnc = EncryptionDecryption.EncryptString((item.queryId).ToString());

                                }
                                <button type="button" class="btn btn-info">@Html.ActionLink("View", "ViewQueryDetails", new {id=queryIdEnc})</button>
                            </td>
                            <td>
                                <i class="bi bi-trash fa-2x" onclick="deleteUserQuery(this,@item.queryId)" style="color:red"></i>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>

Feedback360_Frontend/Views/UserQuery/ViewQueryDetails.cshtml
@model IEnumerable<Feedback360_Frontend.Models.CommentVm>
@{
    ViewData["Title"] = "ViewQueryDetails";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link rel="stylesheet" href="~/css/UserQueries.css" asp-append-version="true" />

<section style="background-color: #eee;">
    <a role="button" class="btn btn-primary" asp-action="UserQueries" asp-controller="UserQuery" style="background-color:#00008b;margin-left:20px;margin-top:10px;">Back</a>

    <div class="container py-5">
        <div class="row">
            <div class="col-md-6 col-lg-5 col-xl-4 mb-4 mb-md-0">
                <div class="border">
                    <div class="card" id="commentInfoCard">
                        <div class="card-header" id="commentInfoHeading">Query Details</div>
                        <div class="card-body">
                            <div class="form-outline mb-4">
                                <h5>Query Title</h5>
                                <h6 class="control-label">@ViewBag.QueryData.queryTitle</h6>
                            </div>
                            <div class="form-outline mb-4">
                                <h5>Description</h5>
                                <h6 class="control-label">@ViewBag.QueryData.description</h6>
                            </div>
                            <div class="form-outline mb-4">
                                <h5>Query Status</h5>
                                @if (@ViewBag.QueryData.queryStatus == "True")
                                {
                                    <h6 class="control-label">Resolve</h6>
                                }
                                else
                                {
                                    <h6 class="control-label">Open</h6>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-7 col-xl-8">
                <div class="card" id="sendCommentCard">
                    <div class="card-header" id="commentInfoHeading">Comments</div>
                    <br />
                    <br />
                    <ul class="list-unstyled">
                        <div id="chatSection">
                            @if (TempData["ViewQueryDetails"] != null)
                            {
                            <li>
                                <div class="alert alert-danger" role="alert">
                                        @TempData["ViewQueryDetails"]
                                </div>
                            </li>
                            }
                            else
                            {
                                @foreach (var item in Model)
                                {
                                    @if (item.RoleName == "Administrator")
                                    {
                                    <li class="d-flex justify-content-between mb-4">
                                        <img src="~/images/UserIcon.png" alt="avatar"
                                 class="rounded-circle d-flex align-self-start ms-3 shadow-1-strong" width="60"> &nbsp;
                                        <div class="card w-100">
                                            <div class="card-header d-flex justify-content-between p-3">
                                                <p class="fw-bold mb-0" id="adminComment">Admin</p>
                                            </div>
                                            <div class="card-body">
                                                <p class="mb-0">
                                                        @item.CommentText
                                                </p>
                                            </div>
                                        </div>
                                    </li>
                                    }
                                    else
                                    {
                                    <li class="d-flex justify-content-between mb-4">
                                        <div class="card w-100">
                                            <div class="card-header d-flex justify-content-between p-3">
                                                <p class="fw-bold mb-0" id="userComment">@item.RoleName</p>
                                            </div>
                                            <div class="card-body">
                                                <p class="mb-0">
                                                        @item.CommentText
                                                </p>
                                            </div>
                                        </div>
                                        <img src="~/images/UserIcon.png" alt="avatar"
                                 class="rounded-circle d-flex align-self-start ms-3 shadow-1-strong" width="60">
                                    </li>
                                    }
                                }
                            }
                </div>
            </div>
            <br />
            <li class="d-flex justify-content-between mb-4">
                <div class="card" id="enterCommentCard">
                    <div class="card-body">
                        <div class="card-header" id="commentInfoHeading">Enter Comment</div>

                        <div class="form-outline">
                            <form asp-action="SendUserComment" class="pt-3" enctype="multipart/form-data">

                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-outline mb-4" hidden>
                                    <label class="control-label"></label>
                                    <input name="queryId" value="@ViewBag.QueryData.queryId" class="form-control" />
                                </div>
                                <div class="form-outline mb-4" id="commentForm">

                                    <div class="card-body">
                                            @if (@ViewBag.QueryData.queryStatus == "True")
                                            {
                                            <textarea class="form-control" id="textAreaExample2" rows="4" name="commentText" maxlength="300" disabled="disabled"></textarea>
                                            }
                                            else
                                            {
                                            <textarea class="form-control" id="textAreaExample2" rows="4" name="commentText" maxlength="300" required ></textarea>
                                            }
                                    </div>
                                </div>
                                <div style="text-align:center" class="form-outline mb-4">
                                    <input type="submit" value="Save" class="btn btn-success" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
        </li>
        </ul>
    </div>
    </div>
    </div>
</section>

Feedback360_Frontend/Views/UserQuery/_UserQueryForm.cshtml
@model Feedback360_Frontend.Models.UserQueryVm
@{
    ViewData["Title"] = "_UserQueryForm";
}
@{
    Layout = null;
}
<head>
 <partial name="_ValidationScriptsPartial" />
 <script src="~/js/Query/UserQuery.js"></script>
<style>
    label {
        color: darkblue;
    }
</style>
</head>
<div class="model-body">
    <div class="outerBox" style="padding:12px;">
        <form asp-action="UserQueryForm" data-ajax="true" data-ajax-method="POST"
          data-ajax-failure="globalFunctions.onFailure"
          data-ajax-success="onSaveSuccess" class="pt-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-outline mb-4" hidden>
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-outline mb-4" hidden>
                <label asp-for="QueryId" class="control-label"></label>
                <input asp-for="QueryId" class="form-control" />
                <span asp-validation-for="QueryId" class="text-danger"></span>
            </div>
            <div class="form-outline mb-4" hidden>
                <label asp-for="QueryStatus" class="control-label"></label>
                <input asp-for="QueryStatus" value="0" class="form-control" />
                <span asp-validation-for="QueryStatus" class="text-danger"></span>
            </div>
            <div class="form-outline mb-4">
                <label asp-for="QueryTitle" class="control-label">Query Title<span style="color:red">*</span></label>
                <input asp-for="QueryTitle" class="form-control" />
                <span asp-validation-for="QueryTitle" class="text-danger"></span>
            </div>
            <div class="form-outline mb-4">
                <label asp-for="Description" class="control-label">Description<span style="color:red">*</span></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <div class="modal-footer">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-info" role="button" data-bs-dismiss="modal">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts{
}